<a href="https://colab.research.google.com/github/nikishkaaa/ML-Course/blob/main/HW_2_3_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np
import pandas as pd

In [4]:
vector = np.random.rand(10,)
vector

array([0.95315392, 0.36262713, 0.62910659, 0.45646684, 0.53342782,
       0.27799079, 0.92566486, 0.37551667, 0.36818761, 0.26152771])

In [7]:
vector.shape

(10,)

In [8]:
matrix = np.array([[11, 14, 17],
          [20, 23, 26],
          [29, 32, 35]])
matrix

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [9]:
matrix.shape

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [15]:
vector = np.round(vector +10, 2)
vector

array([10.95, 10.36, 10.63, 10.46, 10.53, 10.28, 10.93, 10.38, 10.37,
       10.26])

In [16]:
matrix = matrix*2
matrix

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [17]:
vector_new = vector*vector
vector_new

array([119.9025, 107.3296, 112.9969, 109.4116, 110.8809, 105.6784,
       119.4649, 107.7444, 107.5369, 105.2676])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [19]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [25]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [26]:
matrix2 = np.dot(result_matrix, C)
matrix2

array([[0.5202],
       [0.2846]])

In [27]:
matrix3 = np.dot(result_matrix, D)
matrix3

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [28]:
result_matrix_T = result_matrix.T
result_matrix_T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [32]:
vector_T = vector.T
print('Vector: ', vector, 'Розмір: ', vector.shape)
print('Vector транспонований: ', vector_T, 'Розмір: ', vector_T.shape)

Vector:  [10.95 10.36 10.63 10.46 10.53 10.28 10.93 10.38 10.37 10.26] Розмір:  (10,)
Vector транспонований:  [10.95 10.36 10.63 10.46 10.53 10.28 10.93 10.38 10.37 10.26] Розмір:  (10,)


Отже, змін не відбулось

In [37]:
column_vector = np.expand_dims(vector, axis=1)
column_vector, column_vector.shape


(array([[10.95],
        [10.36],
        [10.63],
        [10.46],
        [10.53],
        [10.28],
        [10.93],
        [10.38],
        [10.37],
        [10.26]]),
 (10, 1))

Vector - одномірний масив, column_vector - двовимірний

In [40]:
column_vector_T = column_vector.T
print('Column Vector транспонований: ', column_vector_T, 'Розмір: ', column_vector_T.shape)

Column Vector транспонований:  [[10.95 10.36 10.63 10.46 10.53 10.28 10.93 10.38 10.37 10.26]] Розмір:  (1, 10)
